"""empty message

Revision ID: 0afcaab0ff7d
Revises: 073682308629
Create Date: 2024-02-25 19:19:29.313849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0afcaab0ff7d'
down_revision: Union[str, None] = '073682308629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('uq_review_title', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_review_title', ['title'])

    # ### end Alembic commands ###
