"""empty message

Revision ID: 21e09312ff3c
Revises: fb787ae7e726
Create Date: 2024-02-24 21:50:31.086722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e09312ff3c'
down_revision: Union[str, None] = 'fb787ae7e726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucketcontent')
    op.drop_table('bucketimage')
    op.add_column('bucketlist', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('bucketlist', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketlist', 'image')
    op.drop_column('bucketlist', 'content')
    op.create_table('bucketimage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.TEXT(), nullable=True),
    sa.Column('bucketcontent_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['bucketcontent_id'], ['bucketcontent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bucketcontent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('create_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('bucketlist_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['bucketlist_id'], ['bucketlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
