"""empty message

Revision ID: 677966aee68a
Revises: a003c48e2c18
Create Date: 2024-02-25 09:58:40.072033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677966aee68a'
down_revision: Union[str, None] = 'a003c48e2c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bucketlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_bucketlist_title'), ['title'])
        batch_op.create_foreign_key(batch_op.f('fk_bucketlist_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('bucketlist', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bucketlist_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_bucketlist_title'), type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
