"""empty message

Revision ID: b8c6f62a6e02
Revises: 21e09312ff3c
Create Date: 2024-02-24 22:22:08.491845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c6f62a6e02'
down_revision: Union[str, None] = '21e09312ff3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('user', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_at', sa.DATETIME(), nullable=False))
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
