"""empty message

Revision ID: da1e5c02f54f
Revises: f4e7306c306b
Create Date: 2024-02-24 22:23:30.569150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1e5c02f54f'
down_revision: Union[str, None] = 'f4e7306c306b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('bucketlist', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist', sa.Column('create_at', sa.DATETIME(), nullable=False))
    op.drop_column('bucketlist', 'created_at')
    # ### end Alembic commands ###
