name: Run tests

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  execute_tests:
    name: Install dependencies and execute tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.4"]

    env:
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      SQLALCHEMY_DATABASE_URL: ${{ secrets.SQLALCHEMY_DATABASE_URL }}
      SQLALCHEMY_DATABASE_URL_ASYNC: ${{ secrets.SQLALCHEMY_DATABASE_URL_ASYNC }}
      BE_URL: ${{ secrets.BE_URL }}
      FE_URL: ${{ secrets.FE_URL }}
      UPLOAD_DIR: ${{ secrets.UPLOAD_DIR }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Environment Variables
        run: |
          echo "ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}"
          echo "SECRET_KEY: ${{ secrets.SECRET_KEY }}"
          echo "ALGORITHM: ${{ secrets.ALGORITHM }}"
          echo "SQLALCHEMY_DATABASE_URL: ${{ secrets.SQLALCHEMY_DATABASE_URL }}"
          echo "SQLALCHEMY_DATABASE_URL_ASYNC: ${{ secrets.SQLALCHEMY_DATABASE_URL_ASYNC }}"
          echo "BE_URL: ${{ secrets.BE_URL }}"
          echo "FE_URL: ${{ secrets.FE_URL }}"
          echo "UPLOAD_DIR: ${{ secrets.UPLOAD_DIR }}"

      - name: Run Test
        run: |
          pytest -v
